---
- name: Restart apache
  ansible.builtin.service:
    name: "{{ apache_service_name }}"
    state: restarted

- name: Reload apache
  ansible.builtin.service:
    name: "{{ apache_service_name }}"
    state: reloaded

- name: Reload firewalld
  ansible.builtin.service:
    name: firewalld
    state: reloaded
  when: ansible_os_family == 'RedHat'
