---
- name: Converge
  hosts: all
  become: true

  vars:
    # Test-specific variables
    apache_listen_port: 8080
    apache_vhosts:
      - name: test
        server_name: test.example.com
        document_root: /var/www/test

  tasks:
    - name: Include the apache role
      include_role:
        name: apache
