---
name: CI
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 6 * * 0" # Weekly at 06:00 UTC on Sunday

defaults:
  run:
    working-directory: "moreskylab.apache"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: "moreskylab.apache"

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install test dependencies.
        run: pip3 install yamllint ansible-lint

      - name: Lint code.
        run: |
          yamllint .
          ansible-lint --exclude .github/workflows

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - rockylinux9
          - ubuntu2204
          - debian12

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: "moreskylab.apache"

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install test dependencies.
        run: |
          pip3 install ansible molecule molecule-plugins[docker] pytest-testinfra docker

      - name: Run Molecule tests.
        run: molecule test
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
